services:

  postgres:
    container_name: ${POSTGRES_CONTAINER_HOST}
    image: postgres:16.2-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: ${POSTGRES_PORT}
    volumes:
      - pg_auth_data:/var/lib/postgresql/data

  app:
    container_name: app
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src
    ports:
      - 8001:8001
    environment:
      POSTGRES_HOST: ${POSTGRES_CONTAINER_HOST}
    entrypoint:
      ["make", "run-in-docker"]
    restart: always

volumes:
  pg_auth_data:
    driver: local